city:
  name: "Lviv"
  graph_type: "drive"
  raster_file_population: "src/data/ukr_ppp_2020_constrained.tif"
  distance_matrix: "distance_matrix_lviv.npy"
  distance_matrix: False
  grid_size: 0.0125

ev:
  ev_per_capita: 0.004
  battery_capacity: [50000, 100000]
  avg_consumption_per_km: 159.9

charging_stations:
  types:
    Level_2 7.4kW: 
      cost: 1000.0
      capacity: 7400
    Level_2 22kW: 
      cost: 2000.0
      capacity: 22000
    Level_2 50kW: 
      cost: 8500.0
      capacity: 50000
    Level_3 80kW: 
      cost: 10000.0
      capacity: 80000
    Level_3 120kW: 
      cost: 12000.0
      capacity: 120000
    Level_3 160kW: 
      cost: 15000.0
      capacity: 160000
  max_ports_per_node: 4
  energy_loss: 0.1
  types_list: ["Level_2 7.4kW", "Level_2 22kW", "Level_2 50kW", "Level_3 80kW", "Level_3 120kW", "Level_3 160kW"]

simulation:
  simulation_hours: 24
  initial_soc_range: [0.3, 1.0]
  target_charge: [0.8, 1.0]
  charging_threshold: [0.2, 0.3]
  commute_hours:
    morning: [6, 9]
    evening: [16, 19]

evaluation_weights:
  alpha: 0.001
  beta: 5000
  gamma: 10
  delta: 0.01

genetic_algorithm:
  population_size: 50
  generations: 100
  mutation_rate: 0.1
  crossover_rate: 0.5

particle_swarm_optimization:
  particles: 40
  iterations: 100
  w: 0.3
  c1: 1.5
  c2: 1.5

simulated_annealing:
  initial_temperature: 1000
  cooling_rate: 0.99
  min_temperature: 1
  iterations: 1500
  bad_attempts_limit: 20
